### ISSUE TITLE
Hope to support install to VS2022

### ISSUE THREAD

**Issue by magian1127** [godotengine/godot-csharp-visualstudio#19]

**Comment by Densorius** [comment]
Any update on this since Visual Studio 2022 is now publicly available?

**Comment by Quis-Eric** [comment]
hoping for this feature as well

**Comment by TrulyMen** [comment]
hope soon,thx!

**Comment by GeorgeS2019** [comment]
[VS2022 support !](https://github.com/godotengine/godot-csharp-visualstudio/pull/22)

**Comment by neikeq** [comment]
Closed by #22. The new release only supports VS22. Stay with v1.x for VS19 support.
