### ISSUE TITLE
Can't be installed on VS 2019 Community

### ISSUE THREAD

**Issue by georgescumihail-gh** [godotengine/godot-csharp-visualstudio#3]
![image](https://user-images.githubusercontent.com/66799893/86510926-918f9f00-bdf4-11ea-9c4d-d1243985c8ad.png)

**Comment by EdikTV** [comment]
I've got the problem too
![image](https://user-images.githubusercontent.com/49075243/86519050-b2311680-be3f-11ea-98b7-b3e0b7740ce9.png)

**Comment by neikeq** [comment]
This is the 1.1.1 version right?
What is the Visual Studio version? (you can find this in the about dialog)
Do you get the same error if you install the "Mobile development with .NET" workload manually? (if not already installed)
This page describes how to install workloads: https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio?view=vs-2019

**Comment by georgescumihail-gh** [comment]
Hey @neikeq ! Yes that's correct, the version is 1.1.1. I am using VS 2019 (16.5.3) and just installed "Mobile development with .Net", still nothing, same issue.

**Comment by georgescumihail-gh** [comment]
I just updated VS 2019 to the latest version. It works now! Can't wait to boost my productivity with this addon. Thank you dudes!
![image](https://user-images.githubusercontent.com/66799893/86519766-629e1b00-be3e-11ea-8a58-48d4d06687e8.png)
![image](https://user-images.githubusercontent.com/66799893/86519768-6b8eec80-be3e-11ea-8da8-8f39fdbdc74f.png)

**Comment by neikeq** [comment]
Probably because of the minimum version here:
https://github.com/godotengine/godot-csharp-visualstudio/blob/dfe6a06b9f6952a5b63b72f9f6d32b22d517857f/GodotAddinVS/source.extension.vsixmanifest#L33

We should either document this or lower the version. The latter will require testing to make sure it works.

**Comment by neikeq** [comment]
The minimum version of Godot supported is 3.2.3.

With 3.2.2, you will have to add the following line to your csproj manually:

```xml
    <ProjectTypeGuids>{8F3E2DF0-C35C-4265-82FC-BEA011F4A7ED};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
```

It's still likely for there to be issues, and this version of Godot does not support opening script with Visual Studio from the Godot editor.

**Comment by georgescumihail-gh** [comment]
@neikeq yep! That worked! Thank you! I will try to understand how these visual studio extensions work, and how to debug them . I have no previous experience with them, this is a good opportunity to learn. Thank you again!
