### ISSUE TITLE
Using The Extension With Re-Sharper / Opening cs files from The Godot Editor

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot-csharp-visualstudio#5]
I was waiting fort visual studio integration in Godot , now it comes in 3.2.3 beta .
I have only some feature requests which i guess it must be supported by default .

- When using the extension with JetBrains Re-Sharper and enabling re-sahrper intellisense , the Paths , Signals... suggestions and completion gets disabled .

- Opening a script file from the Godot Editor opens the files in visual studio without getting the file selected in the Solution Explorer 

![image](https://user-images.githubusercontent.com/27586088/87967400-6a5cf100-cac7-11ea-86e2-dc14220dda37.png)

- Finally I have one more Question , is it possible to debug the game running on Android device , is there is a workaround for this ?
Please accept my bad English , Thank you !

**Comment by neikeq** [comment]
>Finally I have one more Question , is it possible to debug the game running on Android device , is there is a workaround for this ?

Not right now, but I plan to add a debug target for this.

**Comment by Jakob-PB** [comment]
Your second point is just how Visual Studio works by default. If you want the solution explorer to sync with the active document press this button:
![sync-with-active.png](https://i.imgur.com/sevSYOO.png)
Or you can have the active item always tracked by default by going to Tools->Options and checking this setting on:
![always-track-option.png](https://i.imgur.com/zZSddAK.png)

**Comment by neikeq** [comment]
>- When using the extension with JetBrains Re-Sharper and enabling re-sahrper intellisense , the Paths , Signals... suggestions and completion gets disabled .

I don't know if there's a way to make it use our Roslyn completion providers with ReSharper.
I would like to add the same code completion to Rider in the future, so if this turns out not to possible then maybe we can re-use the Rider code in VS.

**Comment by MrZak-dev** [comment]
Closing this. most of these features are supported in Godot 4
