### ISSUE TITLE
Run The game from The Editor is No Longer Working when using Play In Editor from VS .

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot-csharp-visualstudio#7]
**OS/device including version:**
Windows 10 

**Issue description:**
When I run the game from the editor Play button it works just fine , as soon as i hit the *Play In Editor* from visual studio, playing the game/scene from the editor is no longer working and it requires a Editor restart .

**Screenshots of issue:**
https://youtu.be/-7Jgz2B5VWE

**Comment by Norrox** [comment]
I can confirm this bug :)
