### ISSUE TITLE
How do I install and activate this addin

### ISSUE THREAD

**Issue by Classy11** [godotengine/godot-csharp-visualstudio#8]
Hello, I would like to try out this addin with Godot 3.2.3 RC3. However I have no idea how to use it! I downloaded and installed the vsix file from the release section successfully but I don't know what I am supposed to do with the contents of the godot-csharp-visualstudio-1.1.1 folder and where to put it. I tried putting it in addons but the Godot editor won't recognise it so I assume that is not the correct way of loading it in.

Any help would be appreciated as well.

**If the installation is non-standard compared to other godot extensions and addons it may be useful to have a quick start/installation guide in the readme!**

**Comment by Classy11** [comment]
Well, it appears to be as simple as just running the vsix file and Visual Studio installs it. One more thing is you can't immediately start opening Godot 3.2.3 projects. You have to create them AFTER you installed this addin so visual studio then starts recognising the projects. IT does not recognise projects created before the addin was installed.
Perhaps something pointing this out in the readme would be useful information.

**Comment by neikeq** [comment]
Yes, you just need to download and execute the vsix from the release: https://github.com/godotengine/godot-csharp-visualstudio/releases/tag/v1.1.1
It will be available in the VS marketplace soon as well.

>One more thing is you can't immediately start opening Godot 3.2.3 projects. You have to create them AFTER you installed this addin so visual studio then starts recognising the projects. IT does not recognise projects created before the addin was installed.

I'm not entirely sure I understand. If it's an old project make sure to open it with Godot 3.2.3 first. Godot will update the ProjectTypeGuids in the csproj for the Visual Studio extension to detect it.

**Comment by Classy11** [comment]
@neikeq Makes sense, got it. Thanks for the help! On my part, this issue can be closed.

**Comment by georgescumihail-gh** [comment]
Does it still work with 3.3?
